#!/usr/bin/env python3

import sys
import os
import argparse
import subprocess





parser = argparse.ArgumentParser(add_help=True, description = 'simlink to HOME/bin')
parser.add_argument('source', 
                        help='source')
parser.add_argument('target',
                        nargs='?',
                        help="target")

args = parser.parse_args(sys.argv[1:])

HOME = os.environ["HOME"]
source_path = os.path.abspath(args.source)

base_name = source_path.split("/")[-1] if not args.target else args.target

target_path = os.path.abspath(f"{HOME}/bin/{base_name}")

try:
    subprocess.call(f"rm {target_path}", shell=True)
except FileNotFoundError:
    pass
    
subprocess.call(f"ln -s {source_path} {target_path}", shell=True)