#!/usr/bin/env python3

import argparse
import sys
import os
from formats import qm_packages


parser = argparse.ArgumentParser(add_help=True, description = 'takes an xyz file and sets up a calc ')
parser.add_argument('file', help='input file -- anything parseable by mdtraj or a Gaussian log file')
parser.add_argument('-m', 
                        type=str, 
                        dest="program",
                        required=True, 
                        choices=["gaussian", "qchem", "molpro"],
                        help='software package')
parser.add_argument('--show',
                        dest="show",
                        action="store_true",
                        help='Print file when finished.'
                        )
args = parser.parse_args(sys.argv[1:])

def get_environment():
    dct = {}
    needed = "HOME REMOTE_DIR RJ_UNAME".split()
    for n in needed:
        dct[n] = os.environ.get(n)
    if dct["RJ_UNAME"] is None:
        dct["RJ_UNAME"] = os.environ.get("REMOTE_USER")
    return dct

env = get_environment()


print(f"""
    #######################################
    #        STARTING   JOB  INPUT        #
    #######################################

    Software: {args.program.capitalize()}
    File: {args.file}
    """)

qm_packages[args.program](args.file, show=args.show, **env)

