#!/usr/bin/env python3

import argparse
import sys
import os
from formats import PKARef
from utils.colors import style
from formats import mass_read


parser = argparse.ArgumentParser(add_help=True, description = 'does stuff with output files')

parser.add_argument('action',
                        choices=["g3", "summarise", "checkopt", "compare"],
                        default="g3",
                        nargs="?",
                        help='What do you want to do? (Default: do G3)'
                        )

parser.add_argument('paths', 
                        nargs="+",
                        help='path to files')
parser.add_argument('-o', 
                        type=str, 
                        dest="outfile",
                        default="energies.csv",
                        help='Where to save energies')
parser.add_argument('-r', '--ref', 
                        type=str, 
                        dest="ref",
                        help='Reference csv')
parser.add_argument('-v', 
                        action='count',
                        dest="verbose",
                        default=0,
                        help='Verbosity.')
parser.add_argument('--debug', 
                        action='store_true',
                        dest="debug",
                        help='Debug.')


args = parser.parse_args(sys.argv[1:])


if args.action == "g3":
    PKARef(**vars(args))
else:
    mass_read(**vars(args))

